_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "6": 4.48.2
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
dataset_fabric:
    value: SimpleDataloader
df_config:
    value:
        cnt: 50000
        count_people: 5
model_params:
    value:
        emb_size: 4
