defaults:
    - _self_

name: "model training"
df_config:
    cnt: 50_000

dataset_fabric: "SimpleDataloader"

train_batch_size: 64
test_batch_size: 64
sample_len: 100

cnt_known_address: 100
model: "BertForTransactionRegressionV1"
model_params:
    # (emb_size * 2 + 4) % num_attention_heads == 0
    emb_size: 4 
    num_attention_heads: 12
    use_compositor: False
    time_features: 2

num_epochs: 100
learning_rate: 3e-4

gamma: 0.8
step_size: 10
time_coef_loss: 1
cnt_last_for_show: 50
seconds_betwen_image_show: 10

model_predictor: "time_cross_predictior"
result_loss: "result_loss_slower_change"
show_img: False

show_batch_size: 300

warmup_epochs: 5
p_change: 0.15
p_msk: 0.15
p_save: 0.15
loggin_each: 5
change_strategy: uniform
loss_fn: criterion

start_epoch: 0