defaults:
    - default
    - _self_


name: "dataset: TimePeaks, model: DotProduct"

df_config:
    cnt: 50_000
    count_people: 20
    cnt_boom: 100
    sigma: 100

dataset_fabric: "DatasetTimeBoomAuthorDependence"

model: "BertForTransactionRegressionV1"

model_params:
    # (emb_size + time_features + 1) * 2 % num_attention_heads == 0
    emb_size: 8
    num_attention_heads: 12
    use_compositor: False # True
    time_features: 3

num_epochs: 100
learning_rate: 0.1

model_predictor: "scalar_dot_predictor" # time_cross_predictior
result_loss: "result_loss_slower_change" # result_loss_slower_change, result_loss_empty