defaults:
    - default
    - _self_


name: "dataset: TwoAddresses, model: mlp"

df_config:
    cnt: 500_000




dataset_fabric: "SimpleDataloader"

model: "BertForTransactionRegressionV1"

model_params:
    # (emb_size + time_features + 1) * 2 % num_attention_heads == 0
    emb_size: 1
    num_attention_heads: 12
    use_compositor: False # True
    time_features: 4

num_epochs: 100
learning_rate: 0.1

model_predictor: "scalar_dot_predictor" # time_cross_predictior
result_loss: "result_loss_empty" # result_loss_slower_change